### PR TITLE
Changes to upload and install Pump on the cluster

### PR DESCRIPTION
**Pull request by CrossfireCurt**
Two things:
- python script changes to upload the pump directory to the resources folder on s3
- bootstrap script (bash) to build and install pump on the EMR cluster

Its worth noting that you can't actually use Pump remotely yet

### CODE REVIEW

**Comment by CrossfireCurt** [comment]
it runs it as the hadoop user, which doesn't have permission to do anything without sudo. Is there a better way? I noticed that the "setup_python" script also uses sudo for all of its commands.

**Comment by CrossfireCurt** [comment]
All of them probably don't need sudo... I'll go through and figure out which ones are absolutely necessary for sudo

**Comment by pmogren** [comment]
I expect it's because you are writing to /etc/pump and /opt/pump.
The usual pattern (e.g. as with drill and zookeeper) is to work within /home/hadoop. You should only need sudo to install and start a service, etc.

**Comment by CrossfireCurt** [comment]
okay, cool... i'll switch the script up to work in there then.

**Pull request merged**
